KTU\DatabaseBundle\Entity\User:
  type: entity
  table: user
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    username:
      type: string
    password:
      type: string
    salt:
      type: string
    email:
      type: string
    isActive:
      type: boolean
    roles:
      type: array