parameters:
#    ktu_test.example.class: KTU\TestBundle\Example

services:
#    ktu_test.example:
#        class: %ktu_test.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
