security:
  role_hierarchy:
    ROLE_ADMIN:       ROLE_USER
    ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

  firewalls:
    secured_area:
      pattern:   ^/admin
      anonymous: ~
      http_basic:
        realm: "Admin area"

  access_control:
    - { path: ^/admin, roles: ROLE_ADMIN }

  providers:
    main:
      entity:
        class: KTU\AppBundle\Entity\User
        property: username

  encoders:
    KTU\AppBundle\Entity\User:
      algorithm: bcrypt
      cost: 12