parameters:
#    ktu_assets.example.class: KTU\AssetsBundle\Example

services:
#    ktu_assets.example:
#        class: %ktu_assets.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
