admin:
    pattern:  /
    defaults: { _controller: KTUAdminBundle:Default:index }

admin.daemon.list:
  pattern: /daemon/list
  defaults: { _controller: KTUAdminBundle:Daemon:list }

admin.daemon.list-item:
  pattern: /daemon/list/item/{id}
  defaults: { _controller: KTUAdminBundle:Daemon:getListItem }
  requirements:
    id: \d+